
const carbonFootprintProduction  = 'A measure of the total amount of greenhouse gases emitted in the production of one item. Mostly originating in energy used during material extraction, component manufacture, assembly and transport. Expressed in the unit of equivalent kg of carbon dioxide (kgCO2eq), accounting for the different global warming potentials of various greenhouse gases.';
const carbonFootprintUsePerYear  = 'A measure of the total amount of greenhouse gases emitted in the use of one item during one year. Mostly originating in the energy generated for the grid and used by the device. Expressed in the unit of equivalent kg of carbon dioxide (kgCO2eq), accounting for the different global warming potentials of various greenhouse gases.';
const circularity = 'The degree to which the material loop of a product is closed, by using recycled materials, repair, refurbishment and remanufacture strategies and by recycling materials at the products end of life. Opposite to linearity; the degree to which the material loop of a product is open, by using virgin materials and generating unrecyclable waste at the products end of life. Expressed as the mass percentage of cycled materials to the total materials.';
const virginMaterials = 'Raw materials extracted from nature for the first time, as opposed to materials that have been used in man made applications before. The extraction of virgin resources often requires significant energy and can result in environmental degradation, habitat destruction, and increased greenhouse gas emissions.';
const eWaste = 'Discarded electronic devices and components. Also known as electronic waste, E-waste is a concern because it likely contains toxic chemicals, and traps valuable resources in waste where it is uneconomical to recover.';
const trueCostsAtPurchase = 'The sum of Sales price and Carbon footprint costs of production. True costs refers to the comprehensive cost of producing a product or service when all direct and indirect factors are considered. In this context, environmental costs are limited to carbon costs of production, use (typically assumed to be four years) and end-of-life, and exclude social costs (e.g. fair wages), economic costs (e.g. long term consequences to material stock) and health costs (e.g. medical costs of health impacts).';
const trueCostsAtOwnership = 'The sum of Total costs of ownership for four years and Carbon footprint costs of the full life cycle. True costs refers to the comprehensive cost of producing a product or service when all direct and indirect factors are considered. In this context, environmental costs are limited to carbon costs of production, use (typically assumed to be four years) and end-of-life, and exclude social costs (e.g. fair wages), economic costs (e.g. long term consequences to material stock) and health costs (e.g. medical costs of health impacts).';
const salesPrice = 'The amount of money in Euro that a buyer is expected to pay to purchase one product from a seller. The sales price is exclusive of VAT, shipping and handling, and the itemised sum of the costs of design, production and margin.';
const carbonFootprintCostsProduction = 'The product of the carbon footprint of production and the current carbon price in Euro on the European Union Emissions Trading System. This dynamic price is published on https://ember-climate.org/data/data-tools/carbon-price-viewer/ and standing at 85.76 Euro per tonne on Agust 31 2023. Since there are different ways to establish a carbon price, the interface allows this price to be set to a custom value.';
const carbonFootprintCostUserPerYear = 'The product of the carbon footprint of use per year and the current carbon price in Euro on the European Union Emissions Trading System. This dynamic price is published on https://ember-climate.org/data/data-tools/carbon-price-viewer/ and standing at 85.76 Euro per tonne on Agust 31 2023';
const containsCriticalMaterials = 'Raw materials that are of high importance in manufacturing of specific technology, where they cannot be replaced with common materials (at least not pratically or economically), but are also characterized by a high risk associated with their supply. This risk can arise due to various factors, such as scarcity, geopolitical issues, human rights violation, regulatory or environmental constraints, economic factors, or concentration of production in a limited number of countries.';
