// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYibT475BnbJsciiTmg7no2XyzYA1upHQ',
    appId: '1:570091056367:web:1764fe60e64c89dadcff1a',
    messagingSenderId: '570091056367',
    projectId: 'replanit-791c4',
    authDomain: 'replanit-791c4.firebaseapp.com',
    storageBucket: 'replanit-791c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeDSC3Sod-sUWdxJi9o0HQ-7oyOL706Bg',
    appId: '1:570091056367:android:bbeba4742c69a8b8dcff1a',
    messagingSenderId: '570091056367',
    projectId: 'replanit-791c4',
    storageBucket: 'replanit-791c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXyqKLu0uAkfask3C790n5jIr9Pog5OqI',
    appId: '1:570091056367:ios:02f54a99476152bfdcff1a',
    messagingSenderId: '570091056367',
    projectId: 'replanit-791c4',
    storageBucket: 'replanit-791c4.appspot.com',
    iosClientId: '570091056367-gvl6i3f1aus0cnt5684068lfaut6ng58.apps.googleusercontent.com',
    iosBundleId: 'com.example.responsiveAdminDashboard',
  );
}
